Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Moustapha\Desktop\TestSuite\TestSuite\BlackBox\Backend\API\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden (CSRF cookie not set.): /get_response/
C:\Users\Moustapha\Desktop\TestSuite\TestSuite\BlackBox\Backend\API\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Moustapha\Desktop\TestSuite\TestSuite\BlackBox\Backend\API\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /get_response/
Bad Request: /get_response/
Bad Request: /get_response/
Bad Request: /get_response/
C:\Users\Moustapha\Desktop\TestSuite\TestSuite\BlackBox\Backend\API\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
Authentication failed using Compute Engine authentication due to unavailable metadata server.
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\Desktop\TestSuite\TestSuite\BlackBox\Backend\API\views.py", line 18, in get_response
    pred = generate_answer(question=question)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\dspy\predict\predict.py", line 49, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\dspy\predict\predict.py", line 91, in forward
    x, C = dsp.generate(template, **config)(x, stage=self.stage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\dsp\primitives\predict.py", line 77, in do_generate
    completions: list[dict[str, Any]] = generator(prompt, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\dsp\modules\google.py", line 159, in __call__
    response = self.request(prompt, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\dsp\modules\google.py", line 143, in request
    return self.basic_request(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\dsp\modules\google.py", line 121, in basic_request
    response = self.llm.generate_content(prompt, generation_config=kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\generativeai\generative_models.py", line 317, in generate_content
    self._client = client.get_default_generative_client()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\generativeai\client.py", line 340, in get_default_generative_client
    return _client_manager.get_default_client("generative")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\generativeai\client.py", line 260, in get_default_client
    client = self.make_client(name)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\generativeai\client.py", line 218, in make_client
    raise e
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\generativeai\client.py", line 210, in make_client
    client = cls(**self.client_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\client.py", line 687, in __init__
    self._transport = transport_init(
                      ^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\grpc.py", line 153, in __init__
    super().__init__(
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\base.py", line 98, in __init__
    credentials, _ = google.auth.default(
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Moustapha\miniconda3\envs\django\Lib\site-packages\google\auth\_default.py", line 691, in default
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
google.auth.exceptions.DefaultCredentialsError: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more information.
C:\Users\Moustapha\Desktop\TestSuite\TestSuite\BlackBox\Backend\API\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Moustapha\Desktop\TestSuite\TestSuite\BlackBox\Backend\API\models.py changed, reloading.
Watching for file changes with StatReloader
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
NumExpr defaulting to 8 threads.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Not Found: /
Not Found: /favicon.ico
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dark_mode.css
Not Found: /static/admin/js/theme.js
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dark_mode.css
Not Found: /static/admin/js/theme.js
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dark_mode.css
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/theme.js
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dark_mode.css
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/js/theme.js
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dark_mode.css
Not Found: /static/admin/js/theme.js
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /
Not Found: /static/admin/css/dark_mode.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin/js/theme.js
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Method Not Allowed: /get_response/
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Not Found: /get_response/def f(a , b): return a + b print(f(5 , 6)) Output 11 write unittest and docstring
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /get_response/
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /get_response/
/home/abbass/TestSuite/BlackBox/Backend/Backend/settings.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /get_response/
/home/abbass/TestSuite/BlackBox/Backend/Backend/settings.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/Backend/settings.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /get_response/
/home/abbass/TestSuite/BlackBox/Backend/Backend/settings.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Bad Request: /get_response/
Bad Request: /get_response/
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/TestSuite/BlackBox/Backend/API/views.py", line 23, in get_response
    test_out=test_out.answer
             ^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/dspy/primitives/example.py", line 25, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{key}'")
AttributeError: 'Prediction' object has no attribute 'answer'
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/TestSuite/BlackBox/Backend/API/views.py", line 23, in get_response
    test_out=test_out.predict
             ^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/dspy/primitives/example.py", line 25, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{key}'")
AttributeError: 'Prediction' object has no attribute 'predict'
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/TestSuite/BlackBox/Backend/API/views.py", line 28, in get_response
    return JsonResponse({'code': code, 'testing code': test_out, 'docstring': doc_out})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/http/response.py", line 733, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Prediction is not JSON serializable
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/TestSuite/BlackBox/Backend/API/views.py", line 23, in get_response
    print(test_out.get())
          ^^^^^^^^^^^^^^
TypeError: Example.get() missing 1 required positional argument: 'key'
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/TestSuite/BlackBox/Backend/API/views.py", line 23, in get_response
    print(test_out.answer)
          ^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/dspy/primitives/example.py", line 25, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{key}'")
AttributeError: 'Prediction' object has no attribute 'answer'
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/TestSuite/BlackBox/Backend/API/views.py", line 28, in get_response
    return JsonResponse({'code': code, 'testing code': test_out, 'docstring': doc_out})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/http/response.py", line 733, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Prediction is not JSON serializable
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
Internal Server Error: /get_response/
Traceback (most recent call last):
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/TestSuite/BlackBox/Backend/API/views.py", line 29, in get_response
    return JsonResponse({'code': code, 'testing code': test_out, 'docstring': doc_out})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/http/response.py", line 733, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abbass/anaconda3/envs/django_env/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Prediction is not JSON serializable
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
/home/abbass/TestSuite/BlackBox/Backend/API/views.py changed, reloading.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Watching for file changes with StatReloader
